fix: 타입 에러로 인한 vercel 빌드 오류
Type error: Type '{ videoId: string; opts: { width: string; height: string; playerVars: { loop: number; controls: number; }; }; containerClassName: string; onReady: (event: any) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<YouTube> & Pick<Pick<Readonly<YouTubeProps>, "className" | ... 13 more ... | "onPlaybackQualityChange"> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.
Property 'containerClassName' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<YouTube> & Pick<Pick<Readonly<YouTubeProps>, "className" | ... 13 more ... | "onPlaybackQualityChange"> & Pick<...> & Pick<...>, never> & InexactPartial<...> & InexactPartial<...>'.